### ISSUE TITLE
Piggyback wont work on 05.06 fx server update

### ISSUE THREAD

**Issue by LySoon** [rubbertoe98/FiveM-Scripts#1]
There is no error on console or f8..
its just not working.. it was working on 19 may update..

**Comment by rubbertoe98** [comment]
Working absolutely fine over here, with the latest server artifacts. Still having issues?

**Comment by LySoon** [comment]
its like working some times...

fx server version : 1320

**Comment by rubbertoe98** [comment]
Can't help without you posting any error messages or more details. My only suggestion is make sure you are very close to the person before typing /piggyback

**Comment by LySoon** [comment]
Gonna try it in 20 mins, i have updated all my things like fx server + essentialmode etc

Sorry i was inactive for a week due to university exam^^

**Comment by LySoon** [comment]
Tried it today, didnt worked again..
Gonna check it tomorrow

**Comment by rubbertoe98** [comment]
Were you running OneSync? If so that has now been fixed

**Comment by rubbertoe98** [comment]
Please update to the latest

**Comment by LySoon** [comment]
Thanks ^^
Gonna try right now

**Comment by LySoon** [comment]
Fixed ^^ Thank you A LOT
