### ISSUE TITLE
/carry radius

### ISSUE THREAD

**Issue by acerampage99** [rubbertoe98/FiveM-Scripts#13]
I'm not sure if I'm missing it or what, but I can't seem to reduce how far you have to be to /carry.  People are /carry the PD just as they go to jail from across the room.

**Comment by TheVortexX** [comment]
You can change the radius when it calls to get the closest player on lines 21 and 33, not sure if it shows up anywhere else as I’m on mobile and it’s hard to see right now. But the value (3 as default) is the range I believe and you should be able to change these values

**Comment by rubbertoe98** [comment]
This is fixed in the latest commit.
